In [1]:
import numpy as np
import pandas as pd
from sklearn.linear_model import LinearRegression
from sklearn.preprocessing import PolynomialFeatures

In [2]:
Results=pd.read_excel('Regressiondata.xlsx','data',index_col=False)

In [3]:
Results

Won  Session_Length  Study_Before  Workout_Before  Time  Day
0    -450.222139              62             1               0     1    0
1    -621.970234             238             1               0     1    0
2    -683.037839             114             0               1     2    0
3    -102.034267             148             0               1     2    0
4     -53.564448             201             0               1     2    0
..           ...             ...           ...             ...   ...  ...
995  1941.149781             220             1               0     0    1
996   388.336412             149             1               1     1    1
997    36.931004              80             0               1     1    0
998  -280.395789             194             1               1     2    1
999   399.682685             134             1               0     0    1

[1000 rows x 6 columns]

In [32]:
x1=np.array(Results["Session_Length"])
x2=np.array(Results["Study_Before"])
x3=np.array(Results["Workout_Before"])
x4=np.array(Results["Time"])
x5=np.array(Results["Day"])
x=np.array([x1,x2,x3,x4,x5])
y=np.array(Results["Won"])

In [33]:
print(x1.shape)
print(x2.shape)
print(x3.shape)
print(x4.shape)
print(x5.shape)
print(y.shape)

(1000,)
(1000,)
(1000,)
(1000,)
(1000,)
(1000,)


In [34]:
#use reshape to make 2 dimensional
x1=np.array(Results["Session_Length"]).reshape(-1,1)

In [35]:
x1.shape

(1000, 1)

In [36]:
model = LinearRegression().fit(x1, y)

In [37]:
rsquare = model.score(x1,y)
print('Coefficient of Determination:', rsquare)

Coefficient of Determination: 0.0063634783954498175


In [38]:
#this shows what it thinks is the average profit per session
#before accounting for time played
model.intercept_

121.26695943423715

In [39]:
#and this is what it thinks time played does to my results
model.coef_

array([-0.84096752])

In [40]:
#predictions based on 5 session lengths
times=np.array([0,20,40,60,80]).reshape(-1,1)
y_pred = model.predict(times)
print('predicted response:', y_pred, sep='\n')

predicted response:
[121.26695943 104.44760897  87.62825851  70.80890805  53.98955759]


In [18]:
##Multiple Regression
#Make X Transposed 
x1=np.array(Results["Session_Length"])
x2=np.array(Results["Study_Before"])
x3=np.array(Results["Workout_Before"])
x4=np.array(Results["Time"])
x5=np.array(Results["Day"])
x=np.array([x1,x2,x3,x4,x5]).T
y=np.array(Results["Won"])

In [19]:
print(x.shape)
print(y.shape)

(1000, 5)
(1000,)


In [20]:
model = LinearRegression().fit(x, y)

In [21]:
rsquare = model.score(x,y)
print('Coefficient of Determination:', rsquare)

Coefficient of Determination: 0.011486542886451123


In [22]:
model.intercept_

40.77183977612166

In [23]:
model.coef_

array([-0.82411149, 32.22733323, -2.51264407, 21.92497363, 39.9720306 ])

In [24]:
#this time use 1,-1 as it is a single data point
#this looks at a 150 min session, where you studied before,
#worked out before, played <1pm, and played tuesday to thursday
session = np.array([150,   1,   1,   0,   0]).reshape(1,-1)
session

array([[150,   1,   1,   0,   0]])

In [25]:
y_pred = model.predict(session)
y_pred

array([-53.13019428])

In [26]:
#Polynomial Regression
transformer = PolynomialFeatures(degree=2, include_bias=False)
transformer.fit(x)
x_ = transformer.transform(x)

In [27]:
#Can be done in one line
x_ = PolynomialFeatures(degree=2,include_bias =False).fit_transform(x)

In [28]:
model=LinearRegression().fit(x_,y)

In [29]:
rsquare = model.score(x_,y)
print('Coefficient of Determination:', rsquare)

Coefficient of Determination: 0.021681615895371986


In [30]:
model.intercept_

94.15304589456181

In [31]:
model.coef_

array([ 6.70004317e-01, -2.89296088e+00, -3.33829049e+01, -1.01354068e+02,
       -1.24569326e+02, -7.33917013e-03,  3.59495931e-01,  8.87372265e-02,
        8.30260949e-02,  3.55640879e-01, -2.89296088e+00, -9.57324238e+01,
       -2.89847219e+01,  5.43071187e+01, -3.33829049e+01,  4.00149070e+01,
        5.15452517e+01,  3.69100622e+01,  2.82669961e+01,  1.49483714e+01])

In [44]:
#*************STATS MODEL***********
import numpy as np
import statsmodels.api as sm

In [62]:
#inputs declared as before
Results=pd.read_excel('Regressiondata.xlsx','data',index_col=False)
x1=np.array(Results["Session_Length"])
x2=np.array(Results["Study_Before"])
x3=np.array(Results["Workout_Before"])
x4=np.array(Results["Time"])
x5=np.array(Results["Day"])
x=np.array([x1,x2,x3,x4,x5]).T
y=np.array(Results["Won"])

In [63]:
print(x1.shape)
print(x2.shape)
print(x3.shape)
print(x4.shape)
print(x5.shape)
print(x.shape)
print(y.shape)

(1000,)
(1000,)
(1000,)
(1000,)
(1000,)
(1000, 5)
(1000,)


In [57]:
#Example adding a constant
x5=sm.add_constant(x5)

In [58]:
x5

array([[1., 0.],
       [1., 0.],
       [1., 0.],
       ...,
       [1., 0.],
       [1., 1.],
       [1., 1.]])

In [64]:
x=sm.add_constant(x)

In [65]:
model= sm.OLS(y,x)

In [66]:
results=model.fit()

In [68]:
results.summary()

<class 'statsmodels.iolib.summary.Summary'>
"""
                            OLS Regression Results                            
==============================================================================
Dep. Variable:                      y   R-squared:                       0.011
Model:                            OLS   Adj. R-squared:                  0.007
Method:                 Least Squares   F-statistic:                     2.310
Date:                Tue, 16 Mar 2021   Prob (F-statistic):             0.0423
Time:                        10:23:25   Log-Likelihood:                -7751.8
No. Observations:                1000   AIC:                         1.552e+04
Df Residuals:                     994   BIC:                         1.555e+04
Df Model:                           5                                         
Covariance Type:            nonrobust                                         
==============================================================================
                 coef    std err          t      P>|t|      [0.025      0.975]
------------------------------------------------------------------------------
const         40.7718     69.078      0.590      0.555     -94.783     176.327
x1            -0.8241      0.333     -2.473      0.014      -1.478      -0.170
x2            32.2273     35.801      0.900      0.368     -38.026     102.481
x3            -2.5126     35.793     -0.070      0.944     -72.751      67.726
x4            21.9250     21.875      1.002      0.316     -21.001      64.851
x5            39.9720     21.830      1.831      0.067      -2.866      82.810
==============================================================================
Omnibus:                       16.595   Durbin-Watson:                   2.019
Prob(Omnibus):                  0.000   Jarque-Bera (JB):               19.412
Skew:                           0.236   Prob(JB):                     6.09e-05
Kurtosis:                       3.493   Cond. No.                         651.
==============================================================================

Warnings:
[1] Standard Errors assume that the covariance matrix of the errors is correctly specified.
"""

In [69]:
results.rsquared

0.011486542886451123

In [70]:
results.rsquared_adj

0.006514141190708811

In [71]:
results.params

array([40.77183978, -0.82411149, 32.22733323, -2.51264407, 21.92497363,
       39.9720306 ])

In [72]:
results.fittedvalues

array([  43.82923438, -101.21438753,  -11.83956668,  -39.85935728,
        -83.53726615,   16.09682814,   29.45823977, -126.06502698,
        -86.00960061, -143.04533168,   44.6182831 ,  -16.6569408 ,
         20.3060282 ,   54.00954602,  -96.48040918,  -11.83431984,
         13.80012149,   38.39173735,  103.58159811,   23.0560662 ,
       -132.29157273,   96.9887062 ,  -29.96477257,   42.38499999,
       -105.96031472,  128.39192795,  -41.55066642,   82.89375771,
        -46.41193957, -152.11055805,  -35.19682586,   -7.26567789,
        -73.31830232,  -35.36720683,  -66.27401106,  -39.81545824,
         61.55191221,   64.76330497,   74.19931148,   26.20210342,
         22.4909783 ,   17.45932418,  -22.31037525,   35.6364525 ,
         12.0632559 ,   91.21992579, -117.04288677,  -48.14355832,
        -27.95020344,   -7.75850598,  -80.41285858,   48.19409001,
          8.85020572,  -38.29618749,  -23.01078136,  -23.54391906,
         33.44706842,   35.91940289,   47.04394198,  -27.12609

In [75]:
#used 6 values because of intercept issue?
session = np.array([0, 150,   1,   1,   0,   0])
results.predict(session)

array([-93.90203406])